language: python
python:
    - "nightly"
    - 3.5
    - 3.6
sudo: false
install:
    - pip install --upgrade pip
    - pip install https://github.com/hyperspy/link_traits/archive/master.zip
    - pip install https://github.com/francisco-dlp/hyperspy/archive/RELEASE_v1.4.zip
    - pip install .[test]
    - export MPLBACKEND=agg
    - pip install pytest-cov codecov --upgrade
script:
    - py.test --cov=hyperspy_gui_ipywidgets -v --pyargs hyperspy_gui_ipywidgets
after_success:
    - codecov
matrix:
    allow_failures:
        - python: "nightly"
